job1:
  script:
    - curl https://raw.githubusercontent.com/Jokero/yandex-cloud-cli-install-for-ci/master/install.sh | bash
    - export PATH=$PATH:~/yandex-cloud/bin
    - yc -v
    -  yc --token $YC_TOKEN --cloud-id $YC_CLOUD_ID --folder-id $YC_FOLDER_ID compute instance list