variables:
  SSH_KEY: cache/sshkey
cache:
  - key: "GLOBAL_CACHE"
    paths:
      - cache/

stages:
  - newvm
  - vmconfig

newvm:
  stage: newvm
  script:
    - curl https://raw.githubusercontent.com/Jokero/yandex-cloud-cli-install-for-ci/master/install.sh | bash
    - export PATH=$PATH:~/yandex-cloud/bin
    - yc -v
    - yc config set compute-default-zone ru-central1-b
    - yc --token $YC_TOKEN --cloud-id $YC_CLOUD_ID --folder-id $YC_FOLDER_ID compute instance list
    - mkdir -p cache
    - "[ -f $SSH_KEY ] || ssh-keygen -b 2048 -t rsa -f $SSH_KEY -q -N \"\""
    - >
     yc 
     --token $YC_TOKEN --cloud-id $YC_CLOUD_ID --folder-id $YC_FOLDER_ID 
     compute instance create 
     --name first-instance 
     --zone ru-central1-a 
     --public-ip 
     --create-boot-disk size=20G,image-folder-id=standard-images,image-family=centos-8 
     --preemptible 
     --core-fraction 20 
     --memory 6 
     --ssh-key $SSH_KEY.pub 
    - >
     yc 
     --token $YC_TOKEN --cloud-id $YC_CLOUD_ID --folder-id $YC_FOLDER_ID 
     compute instance list
    - >
     yc 
     --token $YC_TOKEN --cloud-id $YC_CLOUD_ID --folder-id $YC_FOLDER_ID 
     compute instance get first-instance | grep -v "address: 10"  | grep " address:" | tr -d ' address:' > cache/addr
  artifacts:
    paths:
      - cache/sshkey
      - cache/sshkey.pub
    expire_in: 1 week
  rules:
    - when: never

vmconfig:
  stage: vmconfig
  script:
    - uname -a
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - cat $SSH_KEY | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t -t yc-user@62.84.119.228  < /tmp/shell.sh
    #- ssh -t -t yc-user@'cat cache/addr'  < /tmp/shell.sh
